# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TrwDxwnQ92d-ofhAWuxeDwh3IPWKmbon
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.linear_model import LinearRegression
# from sklearn.model_selection import RepeatedKFold, cross_val_score
# 
# # ==========================================
# # 1. KONFIGURASI HALAMAN
# # ==========================================
# st.set_page_config(page_title="Simulasi Statistik Pekanbaru", page_icon="📊", layout="wide")
# 
# # ==========================================
# # 2. HEADER & SUMMARY METRICS
# # ==========================================
# st.title("📊 Perbandingan Metode Simulasi Statistik")
# st.markdown("**Monte Carlo · Bootstrap · Jackknife · Cross-Validation**")
# st.markdown("*Sumber Data: BPS Kota Pekanbaru (2019-2023) | n = 60 observasi*")
# st.divider()
# 
# col1, col2, col3, col4 = st.columns(4)
# col1.metric(label="Rata-rata PDRB", value="42.7 Juta Rp")
# col2.metric(label="Tingkat Kemiskinan", value="4.81%")
# col3.metric(label="Iterasi Monte Carlo", value="10,000")
# col4.metric(label="Resample Bootstrap", value="1,000")
# st.divider()
# 
# # ==========================================
# # 3. DATA GENERATION (Sesuai Konteks Pekanbaru)
# # ==========================================
# np.random.seed(42)
# kecamatan = ["Tampan", "Payung Sekaki", "Bukit Raya", "Marpoyan Damai", "Tenayan Raya", "Lima Puluh", "Sail", "Pekanbaru Kota", "Sukajadi", "Senapelan", "Rumbai", "Rumbai Pesisir"] * 5
# tahun = np.repeat(np.arange(2019, 2024), 12)
# pdrb = np.random.normal(40, 8, 60)
# kemiskinan = np.maximum(1.5, 8.5 - 0.085 * pdrb + np.random.normal(0, 0.5, 60))
# df = pd.DataFrame({'Kecamatan': kecamatan, 'Tahun': tahun, 'PDRB': pdrb, 'Kemiskinan': kemiskinan})
# 
# # Pembuatan Model Baseline (Regresi Linier)
# X = df[['PDRB']]
# y = df['Kemiskinan']
# model_baseline = LinearRegression().fit(X, y)
# b0, b1 = model_baseline.intercept_, model_baseline.coef_[0]
# y_pred = model_baseline.predict(X)
# sd_residual = np.std(y - y_pred)
# 
# # ==========================================
# # 4. TABS KONTEN
# # ==========================================
# tab_data, tab_mc, tab_boot, tab_jack, tab_cv = st.tabs([
#     "📊 Dataset EDA",
#     "🎲 Monte Carlo",
#     "🔄 Bootstrap",
#     "✂️ Jackknife",
#     "✅ Cross-Validation"
# ])
# 
# # --- TAB 1: DATASET ---
# with tab_data:
#     st.header("Eksplorasi Data BPS Pekanbaru")
#     st.dataframe(df.style.format({"PDRB": "{:.2f}", "Kemiskinan": "{:.2f}%"}), use_container_width=True)
# 
#     st.subheader("Scatter Plot: PDRB vs Kemiskinan")
#     fig, ax = plt.subplots(figsize=(10, 4))
#     ax.scatter(df['PDRB'], df['Kemiskinan'], color='#0ea5e9', alpha=0.7, label="Observasi")
#     ax.plot(df['PDRB'], y_pred, color='#ef4444', linestyle='--', label=f"Regresi: Y = {b0:.2f} + {b1:.3f}X")
#     ax.set_xlabel('PDRB / Kapita (Juta Rp)')
#     ax.set_ylabel('Tingkat Kemiskinan (%)')
#     ax.legend()
#     st.pyplot(fig)
# 
# # --- TAB 2: MONTE CARLO ---
# with tab_mc:
#     st.header("Simulasi Monte Carlo (10.000 Iterasi)")
#     st.info("Mensimulasikan skenario acak berdasarkan asumsi distribusi PDRB Pekanbaru untuk memproyeksikan distribusi tingkat kemiskinan.")
# 
#     # Logic: Bangkitkan 10.000 skenario populasi baru
#     n_sim = 10000
#     mc_means = []
#     for _ in range(n_sim):
#         sim_pdrb = np.random.normal(np.mean(df['PDRB']), np.std(df['PDRB']), 60)
#         sim_y = b0 + b1 * sim_pdrb + np.random.normal(0, sd_residual, 60)
#         mc_means.append(np.mean(sim_y))
# 
#     fig_mc, ax_mc = plt.subplots(figsize=(10, 4))
#     ax_mc.hist(mc_means, bins=50, color='#0ea5e9', alpha=0.7, edgecolor='white')
#     ax_mc.axvline(np.mean(mc_means), color='red', linestyle='dashed', linewidth=2, label=f"Mean: {np.mean(mc_means):.3f}%")
#     ax_mc.set_title("Distribusi Estimasi Kemiskinan (Monte Carlo)")
#     ax_mc.legend()
#     st.pyplot(fig_mc)
# 
# # --- TAB 3: BOOTSTRAP ---
# with tab_boot:
#     st.header("Bootstrap Resampling (1.000 Resample)")
#     st.info("Mengambil sampel ulang dengan pengembalian (with replacement) untuk mengukur ketidakpastian (Standard Error) dari koefisien PDRB tanpa asumsi distribusi normal.")
# 
#     # Logic: Bootstrap resampling pada dataset
#     n_boot = 1000
#     boot_coefs = []
#     for _ in range(n_boot):
#         sample = df.sample(n=60, replace=True)
#         m = LinearRegression().fit(sample[['PDRB']], sample['Kemiskinan'])
#         boot_coefs.append(m.coef_[0])
# 
#     fig_boot, ax_boot = plt.subplots(figsize=(10, 4))
#     ax_boot.hist(boot_coefs, bins=40, color='#8b5cf6', alpha=0.7, edgecolor='white')
#     ax_boot.axvline(np.mean(boot_coefs), color='yellow', linestyle='dashed', linewidth=2, label=f"Koefisien (β1): {np.mean(boot_coefs):.4f}")
#     ax_boot.set_title("Distribusi Bootstrap untuk Koefisien PDRB")
#     ax_boot.legend()
#     st.pyplot(fig_boot)
#     st.write(f"**Bootstrap Standard Error:** {np.std(boot_coefs):.5f}")
# 
# # --- TAB 4: JACKKNIFE ---
# with tab_jack:
#     st.header("Jackknife (Leave-One-Out)")
#     st.info("Menjalankan model 60 kali dengan membuang 1 observasi secara bergiliran. Berguna untuk mendeteksi outlier kecamatan yang sangat mendistorsi model.")
# 
#     # Logic: Leave-One-Out
#     n_obs = len(df)
#     jack_coefs = []
#     for i in range(n_obs):
#         X_j = df[['PDRB']].drop(i)
#         y_j = df['Kemiskinan'].drop(i)
#         m = LinearRegression().fit(X_j, y_j)
#         jack_coefs.append(m.coef_[0])
# 
#     fig_jack, ax_jack = plt.subplots(figsize=(10, 4))
#     ax_jack.plot(range(n_obs), jack_coefs, marker='o', linestyle='-', color='#f59e0b')
#     ax_jack.axhline(np.mean(jack_coefs), color='black', linestyle='--')
#     outlier_idx = np.argmax(np.abs(jack_coefs - np.mean(jack_coefs)))
#     ax_jack.scatter(outlier_idx, jack_coefs[outlier_idx], color='red', s=100, label=f"Outlier Berpengaruh (Obs #{outlier_idx})")
#     ax_jack.set_title("Perubahan Koefisien Regresi jika Observasi ke-i Dibuang")
#     ax_jack.set_xlabel("Indeks Observasi")
#     ax_jack.legend()
#     st.pyplot(fig_jack)
# 
# # --- TAB 5: CROSS-VALIDATION ---
# with tab_cv:
#     st.header("K-Fold Cross Validation (5-Fold, diulang 10 kali)")
#     st.info("Menguji kemampuan prediksi model pada data baru (unseen data). Menghasilkan 50 nilai RMSE.")
# 
#     # Logic: 5-Fold Repeated CV
#     rkf = RepeatedKFold(n_splits=5, n_repeats=10, random_state=42)
#     scores = cross_val_score(LinearRegression(), X, y, scoring='neg_root_mean_squared_error', cv=rkf)
#     rmse_scores = -scores  # Ubah dari negatif ke positif
# 
#     fig_cv, ax_cv = plt.subplots(figsize=(10, 4))
#     ax_cv.bar(range(1, 51), rmse_scores, color='#ef4444', alpha=0.8)
#     ax_cv.axhline(np.mean(rmse_scores), color='black', linestyle='dashed', linewidth=2, label=f"Mean RMSE: {np.mean(rmse_scores):.3f}")
#     ax_cv.set_title("Nilai RMSE pada setiap Fold (50 Evaluasi)")
#     ax_cv.set_xlabel("Iterasi Fold")
#     ax_cv.set_ylabel("RMSE")
#     ax_cv.legend()
#     st.pyplot(fig_cv)